### PR TITLE
Tests: Add UWM fixtures

### LINKED ISSUE #7: UWM Test Fixtures
Pull these fixtures from Google Drive.

### PR DESCRIPTION
**Pull request by ewlarson**
This PR adds the UWM test fixtures from Google Drive. It expands the json schema validation step in our GH CI actions to sanity check GBL and UWM fixtures. It also includes a little helper to render the HTML present in the Rights field values.

Fixes #7

### CODE REVIEW

**Review by srappel — CHANGES_REQUESTED** [review]
@ewlarson There are 4 JSON metadata files in the OpenIndexMaps directory. Could you add those as well?

**Comment by ewlarson** [comment]
Okok @srappel I'm not seeing any Aardvark json files in the OpenIndexMaps directory. Am I missing something here? I see the geojson files, but those aren't Aardvark which GBL needs.

Here's an example Index Map from the GBL test fixture set:
https://github.com/UWM-Libraries/GeoDiscovery/blob/main/test/fixtures/files/gbl_documents/index-map-stanford.json

Look in the "dct_references_s" field value (stringified JSON) where the "https://openindexmaps.org" key points to a geojson file value:

```
...,\"https://openindexmaps.org\":\"https://gist.githubusercontent.com/mejackreed/4a44f1f7cc4fbb926068738e903a9e96/raw/fedfb0e599d647920f084627b7dca8f88a358757/stanford-fb897vt9938.geojson\ ..."
```

That's what we'll need to do here to include these index maps in the application. That dct_references_s field is pretty magical in GBL and a lot of features "key" off of the values present in that Hash.

Let me know if that makes sense or if you have any questions.

**Comment by srappel** [comment]
@ewlarson 

> Okok @srappel I'm not seeing any Aardvark json files in the OpenIndexMaps directory. Am I missing something here? I see the geojson files, but those aren't Aardvark which GBL needs.

My bad, I never moved them into Google Drive. They are there now!

**Comment by srappel** [comment]
@ewlarson ok I've updated the id for the c233bA62500a_BL_Aardvark.json so they should all be unique now.

**Review by srappel — APPROVED** [review]
Looks good!

**Pull request merged**
